# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d75de835d000b08084b28b703115b48"
name = "order-prodcut"
application_url = "https://fr-manage.ecolife-us.com"
#application_url = "https://order-product-store.myshopify.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [
  "products/delete",
  "products/update",
  "app/uninstalled",
  "products/create"
]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers"

[auth]
#redirect_urls = [ "https://fr-manage.ecolife-us.com/api/auth" ]
redirect_urls = [ "https://order-product-store.myshopify.com/api/auth" ]
